# Basic
title: Aaron Li's Blog
subtitle: In solitude, where we are least alone.
welcome_message: This is welcome message.
description: This is description.
# creator: <a href="http://onev.cat">@onevcat</a>

# url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: orange

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Cnblogs, description: My Cnblog, url: 'https://www.cnblogs.com/ac2sherry/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: Aaron Li
    # duoshuo: 
    
# Social
social:
    weibo: ac2sherry
    github: Li-Aaron
    # twitter: 
    # gplus: 107108267983477358170
    mail: ac2sherry@126.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
