# Basic
title: Aaron Li's Blog
subtitle: In solitude, where we are least alone.
welcome_message: Learning everyday, let tomorrow be a better today.
description: 一名萌新程序员.
creator: <a href="https://github.com/Li-Aaron">@Aaron Li</a>

# url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: orange

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit my Blog

# Navigation buttons in the front page.
nav:
    - {title: Old Blog, description: Visit my Cnblog, url: 'https://www.cnblogs.com/ac2sherry/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate, jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: Aaron Li
    # duoshuo: 
    
# Social
social:
    weibo: ac2sherry
    github: Li-Aaron
    # twitter: 
    # gplus: 
    mail: ac2sherry@gmail.com

# Google Analytics
ga:
    id: UA-131530384-1
    host: li-Aaron.github.io
